name: TechTrends - Package with Docker

on:
  push:
    branches:
      - main # Trigger on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Run the action on the ubuntu-latest operating system

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # DockerHub username
          password: ${{ secrets.DOCKER_TOKEN }} # DockerHub token

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Set context to the project directory
          file: Dockerfile # Reference the Dockerfile for the TechTrends application
          push: true # Push the image to DockerHub
          tags: prernasao/techtrends:latest
